# object confidence threshold
conf_thres: 0.001

# IOU threshold for NMS
iou_thres: 0.6

# augmented inference
augment: False

# save image with predictions (for developers)
debug_visualization: False